### ISSUE TITLE
IR decodeIRJson

### ISSUE THREAD

**Issue by romakrau** [atuline/WLED#173]
I take a look in ir.cpp and saw that the decodeIRJson code always check and open the ir.json file. Maybe it need some time and resource to do so.  Is it possible do change this behavior and read the file only once. I ask due to a lake of performance on a SP511E.

**Comment by atuline** [comment]
Our SR fork just inherits IR functionality from AirCoookie's original code. 

I did note the other day that the JSON functionality broke in 0.13.0 b6 (but was working in b5). Blazoncek has since fixed that in the Master, but hasn't release a replacement b6 binary (AFAIK). See the commits around Feb 18th at:

https://github.com/Aircoookie/WLED/commits/master
