### ISSUE TITLE
how to activate infrared  44 key remote in ESP8266 With sound reactive wled? 

### ISSUE THREAD

**Issue by sbali620** [atuline/WLED#186]
how to activate infrared  44 key remote in ESP8266 With sound reactive wled? 
I want to operate it through ir remote? so please do any one have solution?

**Comment by atuline** [comment]
I HIGHLY recommend getting IR running on the orignal version of WLED first, so that you don't have configuration issues if you try to get it running on the SR fork.

In addition, IR has been disabled by default on the SR fork, so you'll need to enable it in wled.h and re-compile.  Note that we don't support IR. Just the web interface.

In my case, I did get it running on the non-SR of WLED (didn't try our fork), and created a customized .json file that used both sets of API's to create the commands I wanted. You'll need to become familiar with the .json files. Here's some links:

https://kno.wled.ge/interfaces/json-ir/json_infrared/
https://kno.wled.ge/interfaces/infrared/
https://kno.wled.ge/interfaces/http-api/
https://kno.wled.ge/interfaces/json-api/#playlists

You'll also want a very new version of WLED, because the json-api wasn't working in b6 for quite sometime.. 

If not already on there, you might want to get onto the WLED Discord, where there are a number of folks able to assist.

Oh, and our sound reactive fork is ONLY up to date with the ESP32. The ESP8266 branch only goes up to 0.12.0.
