### ISSUE TITLE
How to apply wireless data transfer?

### ISSUE THREAD

**Issue by NFTechC** [atuline/WLED#229]
Hi friends, this may be some kind off topic but I applied WLED to the ceiling of my living room and it looks awesome!

Anyway I have a few metres of WS2815 remaining and would like to apply them into a shelv.
As the arduino is located at the ceiling, I need to find a way to transfer data wirelessly from GPIO to the WS2815.

Will some kind of 433MHZ RF LINK KIT work this way?
I dont want two Arduinos to communicate, simplay transfer the GPIO signal wirelessly.

thanks in advance

**Comment by softhack007** [comment]
> simply transfer the GPIO signal wirelessly.

Not sure this will work as you expect. The "GPIO signal" is running at **800K**hz, and timing is critical. 

Assuming you'd manage to feed the signal output into a wireless transceiver, and decode it on the other end without loosing timing information, I'd still expect you have a lot of flashing and flickering, because any 'glitch' of a few microseconds is enough to screw up the WS2815 data protocol.

I think the "usual" solution is to attach your few remaining meters to another ESP (ESP32, or maybe 8266 if you have just a handfull of LEDs). Then use the DDP protocol for controlling these LEDs by the master on your ceiling. All you need for this is a WiFi network. 

https://kno.wled.ge/advanced/ddp/
